### ISSUE TITLE
Rename project to "connector_multiplatform"?

### ISSUE THREAD

**Issue by davidsummers** [warhawkreborn/connector_unix#11]
Should this project now be renamed to one of:

1. connector_multiplatform
2. warhawk-reborn-multiplatform
3. Something else

now that is compiles and runs on at least 4 different platforms:
1. Linux (CentOS 7)
2. Linux (Raspberry Pi) (also probably Debian but untested)
3. MacOS
4. Windows

It may run on more platforms, but those are the ones I've tested.

What do you think?

**Comment by Thalhammer** [comment]
Maybe connector_console might be a good fit ?
Since its a console app.

**Comment by davidsummers** [comment]
I just know that "connector_unix" no longer applies.  :-)

However, "console" implies it runs from the user console (which it does right now) but I want to make it into a "service" that runs in background.

So, maybe something else other than "console" to not have to rename it again once it is no longer running on the console?

Actually, on Centos 7 and Debian/RaspberryPi it is no longer running on the "console", it is just running on the console (currently) on Windows and MacOS.

**Comment by davidsummers** [comment]
Also, in your project description it says 

Connector to allow discovery of servers (Linux & Mac version) 

You can add Windows to that list as well.

I think if you change that description and the project 
then it will be less confusing and more descriptive than what is there now.

Let me know what you think.
