### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by davidsummers** [warhawkreborn/connector_unix#19]
I would love to continue working on this project with @Thalhammer.

I've got 6 issues open (waiting for questions to be answered) and 2 pull requests.

I think I've added significant new functionality in the 2 PRs that would be nice to have in the main branch.

I've been using the "Proxy Server" version I added for several months with no problems noticed.

I think there are a number of new features that would be interesting to work on and discuss.

I know @Thalhammer is in Italy which is hard-hit with the Corona Virus, so I hope he is OK.

I think so, because I've seen him posting in other projects.

If the project is "dead" (I hope not), should I try taking it over?

I only mention the possibility because I've not heard anything now for 3 months.

I would rather work with @Thalhammer than take it over myself.

Please let me know what you think.

   - Thanks
   - David

**Comment by Thalhammer** [comment]
Hi David,
No the project is not dead.
I have just been pretty busy in the last time.
Also I am not in italy (however Corona hit pretty much every country by now so I doubt that makes much difference).
I have seen your changes and issues and once I come around to checking them I will ofc merge them, as I assume it is good work (it has always been so far). I don't look at github that often right now so if you have urgent questions feel free to message me on Discord via Thalhammer#2377.

I'll go through the other issues tomorrow and answer where possible.

**Comment by davidsummers** [comment]
Oh, there you are!  Glad you are OK.

Yes, when you can, please go ahead and merge those changes when you get a chance.

I've been using them on about 4 different systems since they were written.

Thanks!
