### ISSUE TITLE
Create Debian package

### ISSUE THREAD

**Issue by davidsummers** [warhawkreborn/connector_unix#6]
It would be really great to create a Debian package of this software and the systemctl start/stop script which can be used to start and stop the service.

This would also work on Raspberry PI.

I have never attempted building a Debian/Raspberry PI package before but will do so unless some one beats me to it.

For reference, I already have a systemd configuration file in the packages/centos-7 RPM build system and it might either be an exact copy or just a slight modification to get it to build and work on Debian/Raspberry PI.

**Comment by Thalhammer** [comment]
Merged in 0c76cb336edd7d226485fafa620661e32dea96b4

**Comment by davidsummers** [comment]
Wow, that was a lot easier than expected!

I just tested on Raspberry PI and it works great!

I haven't yet learned out how to do so, but was planning on doing it via a debian source package but your way is much simpler.
