### ISSUE TITLE
Create a MacOS Installer package

### ISSUE THREAD

**Issue by davidsummers** [warhawkreborn/connector_unix#7]
It would be really great to create a MacOS package for this software.

I have another project where I have the information needed to do this.

I will probably attempt to do this unless someone else beats me to it.

The only thing I haven't figured out yet is how to start/stop a background "service" on the Mac but I can research it.

**Comment by davidsummers** [comment]
The hosting branch now has a MacOS installer.

However, it doesn't yet have a service start/stop script.

**Comment by davidsummers** [comment]
The packaging branch has updates to build a MacOS PKG file format.

We can also build a DMG file but I have that commented out at the moment unless we want two different MacOS package install experiences:

1. PKG for "system" type package install.
2. DMG for "user" type package install.

**Comment by davidsummers** [comment]
I've got the installers (both PKG and DMG) working now.

Would you like to go ahead and merge the "packaging" branch now (since this issue is about an "installer") or wait until we figure out how to get the program to run in background as a "service"?

I would say go ahead and merge the packaging branch now.

See PR #13 

What do you think?

**Comment by Thalhammer** [comment]
I don't have a mac to test if it works so I will just trust you and assume it does.
Even if it does not, its not that big of a deal anyway.

**Comment by davidsummers** [comment]
I noticed you merged my packaging branch to your packaging branch but didn't merge to master.

Is that on purpose or a mistake?

If not a mistake, was there an issue or something you saw that needed to be addressed before merging to master?

Thanks.

**Comment by Thalhammer** [comment]
Was a mistake, but not a big deal. Fixed it by fast forward merging packaging to master.

I did not change anything, are you sure your PR was correct ?

**Comment by davidsummers** [comment]
"Correct"?   I tested on multiple platforms.  It creates packages for those platforms.

If you had some other meaning of "correct", please let me know and I'd be glad to discuss.

Otherwise, thanks for merging and closing the issue.
