### ISSUE TITLE
Create a Windows Installer package

### ISSUE THREAD

**Issue by davidsummers** [warhawkreborn/connector_unix#8]
It would be great to create a Windows Installer package for this software.

Two free installers systems are:
1. InnoSetup
2. NSIS

Either one would be OK to use, I feel that NSIS is a bit harder to accomplish (more complicated) but it is also more integrated in with CMAKE.

I will attempt this at some point unless someone else beats me to it.

It would be good to have it automatically start/stop the software in a background "service" mode.

**Comment by davidsummers** [comment]
There is now a CMAKE/CPACK/NSIS installer on the packaging branch.

It doesn't yet install a "service" but currently just installs the program which can be manually run.

Later I hope to have it install as a "service" running in background, but this is a start.

**Comment by davidsummers** [comment]
I've got an installer working now.

Would you like to call this issue "finished", since it does create an installer, or would you like to wait until we figure out a way to start the warhawkreborn in a background process to run as a "service" before closing this issue?

I would say go ahead and merge the packaging branch now.

See PR #13 

What do you think?

**Comment by Thalhammer** [comment]
I am not even sure if it is a good idea to install a service on windows.
A windows pc tends to be used for lots of things and at least I like to have as little stuff I don't actively use right now running in the background as possible.
At least we need to make sure the service installation can be deselected on install.

**Comment by davidsummers** [comment]
See my comment on issue #14, I sort of agree, but I think it would be nice to have the OPTION of putting in a Windows background service or not.

I noticed you merged my packaging branch to your packaging branch but didn't merge to master.

Is that on purpose or a mistake?

If not a mistake, was there an issue or something you saw that needed to be addressed before merging to master?

Thanks.
